name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Lint the code (PEP 8 style checks)
    - name: Lint code with pylint
      run: |
        pylint $(git ls-files '*.py')

    # Step 5: Run tests and generate code coverage report
    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml 

    # Step 6: Check code coverage
    - name: Ensure at least 80% code coverage
      run: |
        coverage report --fail-under=80
