name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12
        auto-update-conda: true 

    # Step 3: Create the conda environment
    - name: Create conda environment
      run: |
        conda env create -f environment.yml

    # Step 4: Lint the code (PEP 8 style checks)
    - name: Lint code with pylint
      run: |
        conda run -n myenv pylint $(git ls-files '*.py')

    # Step 5: Run tests and generate code coverage report
    - name: Run tests with coverage
      run: |
        conda run -n myenv coverage run -m pytest
        conda run -n myenv coverage report
        conda run -n myenv coverage xml 

    # Step 6: Check code coverage
    - name: Ensure at least 80% code coverage
      run: |
        conda run -n myenv coverage report --fail-under=80

    # Step 7: Upload Coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
