name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.12  # Ensure it matches your environment

    # Step 2.5: Initialize conda for the shell
    - name: Initialize conda
      run: |
        conda init bash  # Initializes conda for the bash shell
        source ~/.bashrc  # Sources the updated bashrc to apply changes

    # Step 3: Create and activate the conda environment
    - name: Create conda environment
      run: |
        conda env create -f environment.yml
        source activate base
        conda activate myenv

    # Step 4: Lint the code (PEP 8 style checks)
    - name: Lint code with pylint
      run: |
        pylint $(git ls-files '*.py')

    # Step 5: Run tests and generate code coverage report
    - name: Run tests with coverage
      run: |
        coverage run -m pytest
        coverage report
        coverage xml 

    # Step 6: Check code coverage
    - name: Ensure at least 80% code coverage
      run: |
        coverage report --fail-under=80
